
RUBY=BitSet.rb Comp.rb DFA.rb ParserGen.rb Sets.rb Tab.rb Trace.rb module-hack.rb
FRAMES=Parser.frame Scanner.frame

.FORCE: all
all:
	rm -rf build2
	mkdir build2
	cp $(RUBY) $(FRAMES) Coco.ATG build2
	ruby -w Comp.rb build2/Coco.ATG &> build2/output
	(cd build2; ruby -cw *.rb)
	mkdir build2/build3
	cp $(RUBY) $(FRAMES) Coco.ATG build2/build3
	(cd build2; ruby -w Comp.rb build3/Coco.ATG &> build3/output)
