
RUBY=BitSet.rb Comp.rb DFA.rb ParserGen.rb Sets.rb Tab.rb Trace.rb module-hack.rb
FRAMES=Parser.frame Scanner.frame

.FORCE: all
all:
	rm -rf build
	mkdir build
	cp $(FRAMES) *.ATG build
	ruby -w Comp.rb build/Coco.ATG
#	(cd build; ruby -cw *.rb)
